# Generated by Django 4.2.11 on 2024-04-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_created_at_project_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
